/* This file has been generated by the generate-index.py script. Do not edit it will be wiped next time */

export { LoginPage } from './LoginPage';
export { HistoryPage } from './HistoryPage';
export { UsersPage } from './UsersPage';
export { BasePage } from './BasePage';
export { OpenHistoryPage } from './OpenHistoryPage';
export { ScanPage } from './ScanPage';
