services:
    frontend:
        build:
            context: ./docker/node
        container_name: beaussier-frontend
        user: '${USER_ID}:${GROUP_ID}'
        volumes:
            - ..:/home/node/myapp
        command: sh -c "pnpm i && pnpm dev"
        ports:
            - '5173:5173'
        networks:
            - dev
    php:
        build:
            context: ./docker/php
        container_name: beaussier-api
        user: '${USER_ID}:${GROUP_ID}'
        volumes:
            - .:/var/www/html
        expose:
            - 9000
        networks:
            - dev
    web:
        image: nginx
        container_name: beaussier-web
        volumes:
            - .:/var/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8000:80'
        networks:
            - dev

networks:
    dev:
        driver: bridge
